### DISCUSSION TITLE
Problems importing data from LastFM (source) to Maloja (client) and unwanted Lastfm (client) box

### DISCUSSION THREAD

**Discussion by mauriva** [FoxxMD/multi-scrobbler#261] [Q&A] [answered]
I started using Multi Scrobbler (0.9.1) to mirror LastFM data on Maloja (3.2.3).
Initially, the Maloja database was empty.
I started Multi Scrobbler and it detected all the Scrobblers on LastFM (or at least I think it was all of them, since the number shown, about 400, matched the actual number on LastFM). Unfortunately, when I started Multi Scrobbler, Maloja had not yet started, so it could not send the collected data.
When Maloja was started, MS only sent half (200) of the scrobblers.
I restarted Multi Scrobbler (from the web interface in the box I clicked on ‘Restart’) and ended up with ‘Tracks Discovered’ increased to 600, but nothing was uploaded to Maloja. On a further restart of MS the number increased again to 800.
How do I get MS to send all the data collected by LastFM to Majola? Is there any way to force the import?

Finally in the Multi Scrobbler web interface I also find the LastFM (client) box which I don't want to use.
In the file lastfm.json I only entered lastFM as source and the "client" part is deleted.
How do I remove the box (and use LastFM only as source)?

**Comment by FoxxMD** [comment]
MS is not designed or intended to be used to import all of your scrobbles into Maloja. It's designed to be a real-time scrobble/monitor application. The backlog functionality is a convenience for scrobbling any missing activity that may have occurred while MS was down (due to internet outage, crash, computer shutdown, etc...).

Instead, you should use [Maloja's import functionality](https://github.com/krateng/maloja?tab=readme-ov-file#data) with the recommended last.fm csv export website to get your scrobbles into Maloja.

I don't know how or why the UI would show more than 200 discovered on startup since that is the maximum number of tracks it can get from the LFM API at once. That may be a UI bug rather than MS actually finding that many.

> How do I remove the box (and use LastFM only as source)?

I need to see the ENVs and any config files you are using with MS to determine why you are seeing both LFM client/source.

**Comment by mauriva** [comment]
Thank you for your reply.
Unfortunately I had to stop my tests with Multi Scrobbler.
After its installation, my virtual machine on Oracle Free Tier had become unusable (I could not figure out why: too much memory occupied? too much CPU? too much bandwidth?). After stopping the docker my VM was usable again....

**Reply by FoxxMD** [reply]
If you could provide any logs from when it was running that would still be helpful. From the time it was increasing LFM discovered tracks. And your ENV/configs would still be helpful in possibly making this reproducible, even if it isn't running.

**Reply by mauriva** [reply]
Thank you for your reply.
At the moment I have removed everything and unfortunately I don't have time to do any more tests in the next few days.
I hope to be able to resume next week.

**Comment by mauriva** [comment]
I'm back with this post after several months.
I reinstalled both Maloja (3.2.3) and Multi-Scrobbler (0.9.10) on my home server to do what I described in my first post (mirroring scrobbler data from Lastfm to Maloja).
To install Multi-Scrobbler, I used docker-compose, and here is my .yml file:

```
services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=Europe/Rome
      - BASE_URL=http://myServerIP:9078
      - LASTFM_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxx
      - LASTFM_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxx
      - MALOJA_URL=http://myServerIP:42010
      - MALOJA_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
      - PUID=1000
      - PGID=1000

    volumes:
      - "./config:/config"
    ports:
      - "9078:9078"
    restart: unless-stopped
```

After that, I created the lastfm.json file with this content:
```
[
  {
    "name": "myLastFmSource",
    "enable": true,
    "configureAs": "source",
    "data": {
      "apiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "redirectUri": "http://myServerIP:9078/lastfm/callback"
    }
  }
]
```

Now everything seems to be working correctly, but the Multi-Scrobbler screen still shows a second lastfm (client) box, and I don't know how to remove it.
Did I do something wrong in the configuration? Do I need to remove the two Lastfm entries from the yml file?
<img width="1011" height="442" alt="immagine" src="https://github.com/user-attachments/assets/a7aeafda-9254-42d8-9a06-1e344cd46061" />
