### DISCUSSION TITLE
Plex scrobble issue

### DISCUSSION THREAD

**Discussion by bleeblonks** [FoxxMD/multi-scrobbler#313] [Q&A]
It seems to be trying to connect to 192.168.1.232:32400 which is my proxy but my plex isnt on the same host and is an LXC rather than a docker container I believe it has something to do with my proxy configuration but i am not quite sure. No other issues with my plex exist and i am able to reach locally and externally. I have set jellyfin configuration the exact same way and have no issues. If anyone could point me in the right direction, that would be much appreciated.

Here is my compose:
```yaml
multi-scrobbler:
    image: foxxmd/multi-scrobbler:latest
    container_name: multi-scrobbler
    environment:
      - TZ=America/Los_Angeles # Specify timezone from TZ Database name found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - SPOTIFY_CLIENT_ID=redacted
      - SPOTIFY_CLIENT_SECRET=redacted
      - SPOTIFY_REDIRECT_URI=redacted/callback ## Need to be whitelisted in Spotify dashboard and is used for creating the connecti>
      - PLEX_URL=https://exaxmple.domain.com:32400
      - PLEX_TOKEN=redacted token
      - JELLYFIN_URL=https://example.domain.com
      - JELLYFIN_USER=user redacted
      - JELLYFIN_APIKEY=redacted token
      - DEEZER_ARL=redacted
      #- MALOJA_URL=http://maloja:42010
      #- MALOJA_API_KEY=
      - PUID=1000 # required if running docker on linux host, see main README Docker setup instructions
      - PGID=1000 # required if running docker on linux host, see main README Docker setup instructions
      # set if using a source/client with redirect URI that you have not explicitly set and MS is NOT running on the same machine that you will view the dashbo>
      # EX: You will view MS dashboard at 'http://192.168.0.101:9078' -> set BASE_URL=http://192.168.0.101:9078
      - BASE_URL=http://192.168.184:9078
    volumes:
      - "/docker/multi-scrobbler/config:/config"
    #networks:
    #  - (optional to add container to the same bridge network that maloja is inside to be able to use docker internal networking & dns to resolve and connect >
    ports:
      - 9078:9078 # first port is the HOST port multi-scrobbler will serve UI and API on
    restart: unless-stopped
```

This is the error log:
```
[2025-06-25 07:28:45.114 -0700] ERROR  : [App] [Sources] [Plex - unnamed] Could not initialize source automatically
Error: Could not initialize source automatically
    at PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatSources.ts:26:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
caused by: Error: Initialization failed
    at PlexApiSource.initialize (CWD/src/backend/common/AbstractComponent.ts:82:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PlexApiSource.tryInitialize (CWD/src/backend/common/AbstractComponent.ts:102:20)
    at async PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatSources.ts:24:29)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
caused by: Conenction Check: Communicating with upstream service failed
    at PlexApiSource.checkConnection (CWD/src/backend/common/AbstractComponent.ts:242:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PlexApiSource.initialize (CWD/src/backend/common/AbstractComponent.ts:69:13)
    at async PlexApiSource.tryInitialize (CWD/src/backend/common/AbstractComponent.ts:102:20)
    at async PromisePoolExecutor.handler (CWD/src/backend/tasks/heartbeatSources.ts:24:29)
    at async PromisePoolExecutor.waitForActiveTaskToFinish (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:375:9)
    at async PromisePoolExecutor.waitForProcessingSlot (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:368:13)
    at async PromisePoolExecutor.process (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:354:13)
    at async PromisePoolExecutor.start (CWD/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:273:16)
caused by: Error: connect ECONNREFUSED 192.168.1.232:32400
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
```

![image](https://github.com/user-attachments/assets/ae2707db-fd3d-4c37-ac74-496343925a20)
