### ISSUE TITLE
Simply doesnt work for Navidrome (Subsonic)

### ISSUE THREAD

**Issue by kobayashi90** [FoxxMD/multi-scrobbler#129]
[Please check the FAQ](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md) before submitting a bug report.

**Describe the bug**

What is the URL for Navidrome Sources, its not the documented one because it fails???
![raw](https://github.com/FoxxMD/multi-scrobbler/assets/51263756/f3885f87-f993-4abb-b165-01b3106ddd07)

**To Reproduce**

docker-stack:
```
version: '3.7'
services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler:latest
    container_name: multi-scrobbler
    environment:
      - TZ=Etc/GMT # Specify timezone from TZ Database name found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- SPOTIFY_CLIENT_ID=
      #- SPOTIFY_CLIENT_SECRET=
      #- SPOTIFY_REDIRECT_URI=http://multi-scrobbler-host-IP:9078/callback ## Need to be whitelisted in Spotify dashboard and is used for creating the connection first time
      - MALOJA_URL=http://172.20.0.2:42010
      - MALOJA_API_KEY=lrxydQhqFz9VKgkDBT5CDK9iqNpiL4yZv8XARU5K0tsiaT1WyLSrnrE1wGZOc6Ao
      - PUID=0 # required if running docker on linux host, see main README Docker setup instructions
      - PGID=0 # required if running docker on linux host, see main README Docker setup instructions
      - SUBSONIC_USER=Guest
      - SUBSONIC_PASSWORD=Guest
      - SUBSONIC_URL=http://192.168.16.3:4533
      # set if using a source/client with redirect URI that you have not explicitly set and MS is NOT running on the same machine that you will view the dashboard from
      # EX: You will view MS dashboard at 'http://192.168.0.101:9078' -> set BASE_URL=http://192.168.0.101:9078
      #- BASE_URL=http://MyHostIP:9078


    volumes:
    - "/opt/multi-scrobbler:/config"
    #networks:
    #  - (optional to add container to the same bridge network that maloja is inside to be able to use docker internal networking & dns to resolve and connect to maloja URL via http://maloja:port)
    ports:
    - 9078:9078 # first port is the HOST port multi-scrobbler will serve UI and API on
    restart: unless-stopped
```

**Expected behavior**

To work and maybe have an more up to documentation?

**Logs**
If possible reproduce the issue with [debug logging ON](https://github.com/FoxxMD/multi-scrobbler/blob/master/docsite/docs/FAQ.md#turn-on-debug-logging)

```
Copy and paste as much log data as possible related to this issue here.
```

**Versions (please complete the following information):**
Provide version information for any related sources/clients.

- multi-scrobbler: [latest]
- maloja [latest]
- navidrome [latest]

**Additional context**
