### ISSUE TITLE
Last.fm scrobbles are not being identified.

### ISSUE THREAD

**Issue by Ardakilic** [FoxxMD/multi-scrobbler#133]
Hello, 

I'm trying to periodically sync last.fm scrobbles to my maloja instance. Recently I stumbled upon Reddit  on about this repository, hope you remember :) 

Today I got the chance to try it out, but it simply does not work for me on last.fm.

Here's roughly the corresponding part of my docker compose file:

```yaml
multi-scrobbler:
  image: foxxmd/multi-scrobbler
  container_name: multi_scrobbler
  environment:
    - TZ=Europe/Istanbul
    - MALOJA_URL=http://maloja:42010
    - MALOJA_API_KEY=
    - LASTFM_API_KEY=
    - LASTFM_SECRET=
    - LASTFM_REDIRECT_URI=http://publicurl/lastfm/callback
    - PUID=1000
    - PGID=1000
    - LOG_LEVEL=debug
  volumes:
    - /home/arda/docker/multiscrobbler:/config
  ports:
    - localport:9078
  restart: unless-stopped
  networks:
    - ardanet
```

After the initial boot, I authenticated last.fm, and restarted the container, and its status went green and tokens could show my last.fm username correctly.

The token's callback url matches with mine.

<img width="871" alt="image" src="https://github.com/FoxxMD/multi-scrobbler/assets/2063957/ad110339-0a9a-4dd6-aad3-8e723ca532cf">

Here's my last.fm user, if that would matter: https://www.last.fm/user/ardadev

I attached my debug logs, if that would matter, but I could not make it out much.

Also, I waited for 20 mins for periodic schedule check, still nothing.

Could you check please? What am I missing?

Thanks in advance!

[scrobble-2024-01-30.log](https://github.com/FoxxMD/multi-scrobbler/files/14091255/scrobble-2024-01-30.log)
