### ISSUE TITLE
show "Cannot GET /" when visit dashboard.

### ISSUE THREAD

**Issue by niumeng07** [FoxxMD/multi-scrobbler#187]
show "Cannot GET /" when visit dashboard.

image_id: c3cc681f8553

install with docker-compose
```
services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler-1
    network_mode: bridge
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - BASE_URL="http://192.168.3.118:9078"
    volumes:
      - /volume1/docker/multiscrobbler:/config
    ports:
      - 9078:9078
    restart: unless-stopped
```

I also tried set network_mode host, same error follows.
