### ISSUE TITLE
A few things on the documentation

### ISSUE THREAD

**Issue by iluvatyr** [FoxxMD/multi-scrobbler#55]
## 1) Docker run example mistake?

In the docker run example, it shows following:

`docker run -e "SPOTIFY_CLIENT_ID=yourId" -e "SPOTIFY_CLIENT_SECRET=yourSecret" -e "MALOJA_URL=http://domain.tld" -e "MALOJA_API_KEY=1234" -v /path/on/host/config:/home/node/app/config foxxmd/multi-scrobbler`

When I finished my setup and connected via spotify, I noticed that there was a docker volume that was created automatically by multiscrobbler to have **`/home/node/config`** mounted inside the container, in which an actual personal configuration (currentCreds-unnamed.json) is saved, whereas the directory shown in the docker run command above **`/home/node/app/config`** just holds the json examples from [here](https://github.com/FoxxMD/multi-scrobbler/tree/master/config).
Is the docker run command by any chance using the wrong path and it should be **`/home/node/config`**?
At least looking at [configuration.md](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/configuration.md) seems to confirm what I think.

## 2 Unifying environment variables
Regarding the Environment variables of LOG_PATH and CONFIG_DIR, I wanted to just point out, that they could be unified in naming, since they are both directories / paths. (LOG_PATH & CONFIG_PATH or LOG_DIR & CONFIG_DIR ). This could be easily done by just adding another environment variable while still being backward compatible.

## 3 Automatic docker volume creation is not mentioned
When no bind mount or volume is set for the log and config directory, the container is creating them automatically, maybe this could be mentioned also (at least this was the case for me). I think it would be good to mention this, since otherwise some people will wonder at some point why they have some docker volumes suddenly.

## 4) Docker compose
Talking about the README.md, it would be also cool to include a docker-compose.yaml. A lot of people use those to run containers. For example something like this.

```
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=Eurrope/London
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
      - SPOTIFY_REDIRECT_URI=http://multi-scrobbler-host-IP:9078/callback ## Need to be whitelisted in Spotify dashboard and is used for creating the connection first time
      - MALOJA_URL=http://maloja:42010
      - MALOJA_API_KEY=
      - PORT=9078 # optional
      - CONFIG_DIR=/home/node/config #optional
      - LOG_PATH=/home/node/logs # optional 
    volumes:
       - /path_on_host/multi-scrobbler-config:/home/node/config
    #networks:
    #  - (optional to add container to the same bridge network that maloja is inside to be able to use docker internal networking & dns to resolve and connect to maloja URL via http://maloja:port)
    ports:
      - 9078:9078
    restart: unless-stopped
```

## 5) Add Timezon (TZ) to environment variables 
Just adding it to the documentation would probably be helpful to some, so that they know it can be used to set the correct timezone for their multi-scrobbler container. Otherwise the logs show the wrong time.
