### ISSUE TITLE
No source with the name [unnamed-mlj] and type [maloja

### ISSUE THREAD

**Issue by purashy** [FoxxMD/multi-scrobbler#97]
An issue I am running into is that spotify works fine, but maloja, listenbrainz and lastfm are not. When trying to "authenticate", I get the following message:

> No source with the name [unnamed-lz] and type [listenbrainz

> No source with the name [unnamed-lfm] and type [lastfm

> No source with the name [unnamed-mlj] and type [maloja

I am not using any configs etc.

**This is purely how I set it up:**
- Copy yaml
- docker-up it (I use portainer)
- Navigate to url + click auth on spotify, works.
- Try to auth with other 3, errors above.

Using [Maloja v3.1.5](https://github.com/krateng/maloja/releases/tag/v3.1.5), and multi-scrobbler develop branch.

**My docker-compose:**

```yaml
version: '3.7'

services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler:develop
    container_name: multi-scrobbler
    environment:
      - TZ=Cont/TZ
      - SPOTIFY_CLIENT_ID=x
      - SPOTIFY_CLIENT_SECRET=x
      - SPOTIFY_REDIRECT_URI=http://192.168.x.x:9078/callback
      - MALOJA_URL=http://192.168.x.x:9003
      - MALOJA_API_KEY=x
      - LASTFM_API_KEY=x
      - LASTFM_SECRET=x
      - LZ_TOKEN=x-x-x-x-x
      - LZ_USER=syber
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/syber/multiscrobbler/config:/config
    ports:
      - 9078:9078
    restart: unless-stopped
```

**Comment by FoxxMD** [comment]
@syberslxt please try using `foxxmd/multi-scrobbler:develop` docker image.

You will also need to set a [redirect URL for lastfm.](https://foxxmd.github.io/multi-scrobbler/docs/configuration#env-based-11)

You can do it using the env variable found in the config OR you can use a new env `BASE_URL` to set the default redirect url for both lastfm and spotify like this:

```yaml
version: '3.7'

services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler:develop
    container_name: multi-scrobbler
    environment:
      - TZ=Cont/TZ
      - BASE_URL=http://192.168.x.x:9078
      - SPOTIFY_CLIENT_ID=x
      - SPOTIFY_CLIENT_SECRET=x
      - MALOJA_URL=http://192.168.x.x:9003
      - MALOJA_API_KEY=x
      - LASTFM_API_KEY=x
      - LASTFM_SECRET=x
      - LZ_TOKEN=x-x-x-x-x
      - LZ_USER=syber
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/syber/multiscrobbler/config:/config
    ports:
      - 9078:9078
    restart: unless-stopped
```
